spring:
  datasource:
    # 로컬 테스트용
#    url: jdbc:mysql://localhost:3306/fossistant
#    username: ${LOCAL_DB_NAME}
#    password: ${LOCAL_DB_PW}

    # Azure Database 배포용
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://fossistantdb.mysql.database.azure.com:3306/fossistantdb?sslMode=REQUIRED
      username: ${AZURE_DB_USERNAME}
      password: ${AZURE_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update       # ※운영 환경에서는 create → update
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: never

  data:
    redis:
      host: redis # ※운영 환경에서는 localhost → redis
      port: 6379

  gemini:
    api-key: ${GEMINI_KEY}
    chat:
      model: gemini-2.0-flash

  github:
    token: ${GITHUB_TOKEN}


  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}

logging:
  level:
    root: INFO
    Capstone.FOSSistant.global: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
  security:
    enabled: false