spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 로컬 테스트용
    # url: jdbc:mysql://localhost:3306/gdg
    # username: ${LOCAL_DB_NAME}
    # password: ${LOCAL_DB_PW}

    # Azure Database for MySQL (Flexible Server) 배포용
    url: jdbc:mysql://fossistantdb.mysql.database.azure.com:3306/fossistantdb?sslMode=REQUIRED
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update       # ※운영 환경에서는 create → update 로만 쓰세요
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: never
#jwt:
#  secret: ${JWT_SECRET_KEY}
#  access-token-validity: ${JWT_ACCESS_TOKEN_TIME}
#  refresh-token-validity: ${JWT_REFRESH_TOKEN_TIME}